/**
 * propose_post_from_media — Director's creation-session tool.
 *
 * Takes a list of media_ids (1-10), reads each row's visual_analysis
 * metadata (already generated by /api/media/[id]/analyze when applicable),
 * and delegates to Content & Copy for a structured proposal:
 *   { hook, caption, hashtags[], post_type, rationale }
 *
 * This is the "Ask Director for an idea" brain. The user (or an MCP client
 * on behalf of the user) picks media, asks for an idea, and gets a proposal
 * they can iterate on via normal conversation. When they approve, the
 * Director then calls draft_post (or publish_to_social) with the finalised
 * copy — this tool does NOT insert into scheduled_posts itself.
 *
 * Important: Content & Copy writes everything. This tool is a pass-through
 * wrapper that prepares the brief and parses the JSON envelope. Never
 * allow the calling agent to bypass Content & Copy and write copy itself.
 */

import { tool } from 'ai'
import { z } from 'zod/v3'
import type { SupabaseClient } from '@supabase/supabase-js'
import { runAgentWorker } from '@/lib/agents/worker'
import type { Brand } from '@/types/database'

const PLATFORMS = ['instagram', 'facebook', 'linkedin', 'tiktok', 'youtube', 'twitter'] as const
type Platform = (typeof PLATFORMS)[number]

const PLATFORM_GUIDANCE: Record<Platform, string> = {
  instagram:
    'Instagram caption — hook in first line, 3-5 short paragraphs, conversational, ends with a CTA or question. ~150 words ideal. Reels need a 1-second hook.',
  facebook:
    'Facebook caption — slightly longer than Instagram, more narrative, ends with a question or community prompt. ~200 words.',
  linkedin:
    'LinkedIn caption — professional but human, hook in first 3 lines (before the "see more" cutoff), short paragraphs. ~250 words.',
  tiktok:
    'TikTok caption — very short (~100 words max), punchy, leans on the video, ends with a hook for replies.',
  youtube:
    'YouTube description — first 2 lines are the hook (above the fold). For Shorts, keep <300 words. Long-form can run longer.',
  twitter: 'X/Twitter post — 280 character hard limit. One sharp idea.',
}

export interface PostProposal {
  hook: string
  caption: string
  hashtags: string[]
  post_type: 'single' | 'carousel' | 'reel' | 'video'
  rationale: string
}

interface MediaDescriptor {
  id: string
  file_name: string
  file_type: string
  summary: string | null
  products: string[]
  scenes: string[]
  mood: string | null
  transcription: string | null
}

export function createProposePostTool(
  supabase: SupabaseClient,
  userId: string,
  brandId: string,
) {
  return tool({
    description: `Propose a creative post idea from a list of media items. Use this when the user has selected media (1 video or 1-10 images) and asks "what should I post about this?", "give me an idea", or similar creative starting prompts. DO NOT write the post yourself — this tool delegates to Content & Copy and returns their structured proposal so you can present it to the user for iteration.

The tool reads existing visual_analysis metadata on each media_item (no new vision call) so Content & Copy can write based on actual scene descriptions, products visible, mood, and any transcription.

After you present the proposal, wait for user feedback. On "make it [different]" feedback, call this tool again with the same media_ids plus a "previous_proposal" and "user_feedback" field so Content & Copy can iterate. When the user approves, call draft_post with the finalised caption + hashtags + media_id (for single-media posts).

CRITICAL: never supply the caption or hashtags yourself. Pass the user's angle hint verbatim. Content & Copy owns the words.`,
    inputSchema: z.object({
      media_ids: z
        .array(z.string().uuid())
        .min(1)
        .max(10)
        .describe('UUIDs of media_items rows to base the proposal on. Get these from query_media.'),
      platform: z
        .enum(PLATFORMS)
        .describe('Which platform the post is for'),
      angle: z
        .string()
        .optional()
        .describe('Optional user-supplied angle or theme hint, e.g. "fragrance authentication", "behind the scenes", "customer testimonial"'),
      previous_proposal: z
        .string()
        .optional()
        .describe('For iteration: the JSON of the previous proposal returned by this tool. Content & Copy sees what it wrote last time.'),
      user_feedback: z
        .string()
        .optional()
        .describe('For iteration: the user\'s feedback on the previous proposal. e.g. "more playful", "shorter hook", "emphasise the smell notes"'),
    }),
    execute: async ({ media_ids, platform, angle, previous_proposal, user_feedback }) => {
      // 1. Fetch the brand for Content & Copy's context
      const { data: brand, error: brandError } = await supabase
        .from('brands')
        .select('*')
        .eq('id', brandId)
        .eq('user_id', userId)
        .single()

      if (brandError || !brand) {
        return 'Error: Brand not found or access denied.'
      }
      const typedBrand = brand as Brand

      // 2. Fetch each media row with its visual analysis
      const { data: items } = await supabase
        .from('media_items')
        .select('id, file_name, file_type, metadata, transcription')
        .in('id', media_ids)
        .eq('brand_id', brandId)

      if (!items || items.length === 0) {
        return `Error: None of the provided media_ids belong to this brand. Call query_media first to get valid UUIDs.`
      }

      const foundIds = new Set(items.map((i) => i.id))
      const missing = media_ids.filter((id) => !foundIds.has(id))
      if (missing.length > 0) {
        return `Error: ${missing.length} media_id(s) not found for this brand: ${missing.join(', ')}. Call query_media first.`
      }

      // 3. Build descriptor for each item (pulling visual_analysis out of metadata)
      const descriptors: MediaDescriptor[] = items.map((item) => {
        const meta = (item.metadata as Record<string, unknown>) ?? {}
        const va = meta.visual_analysis as
          | {
              summary?: string
              scenes?: string[]
              products?: string[]
              mood?: string
            }
          | undefined
        return {
          id: item.id,
          file_name: item.file_name ?? 'untitled',
          file_type: item.file_type ?? 'unknown',
          summary: va?.summary ?? null,
          products: va?.products ?? [],
          scenes: va?.scenes ?? [],
          mood: va?.mood ?? null,
          transcription: item.transcription ?? null,
        }
      })

      // 4. Build the brief for Content & Copy — rich context, strict JSON envelope
      const mediaSection = descriptors
        .map((d, i) => {
          const lines = [`Media ${i + 1} (${d.file_type}):`]
          if (d.summary) lines.push(`  Summary: ${d.summary}`)
          else lines.push(`  Summary: (no visual analysis yet — use file name "${d.file_name}" and brand context)`)
          if (d.products.length) lines.push(`  Products visible: ${d.products.join(', ')}`)
          if (d.scenes.length) lines.push(`  Scenes: ${d.scenes.slice(0, 3).join(' | ')}`)
          if (d.mood) lines.push(`  Mood: ${d.mood}`)
          if (d.transcription) {
            const preview = d.transcription.length > 300 ? d.transcription.slice(0, 300) + '…' : d.transcription
            lines.push(`  Transcript excerpt: "${preview}"`)
          }
          return lines.join('\n')
        })
        .join('\n\n')

      const iterationSection = previous_proposal
        ? `\n\n### Previous proposal (iterate on this):\n${previous_proposal}\n\n### User feedback on the previous proposal:\n"${user_feedback ?? '(no specific feedback — they said "try again")'}"\n\nAdjust the hook, caption, hashtags, or post_type based on the feedback. Keep what's working. Change what isn't.`
        : ''

      const brief = [
        `You are being asked to propose a ${platform} post for ${typedBrand.name}.`,
        '',
        `### Media selected by the user (${descriptors.length} item${descriptors.length === 1 ? '' : 's'}):`,
        mediaSection,
        '',
        `### Platform format: ${PLATFORM_GUIDANCE[platform]}`,
        '',
        angle ? `### User's angle / theme hint: "${angle}"` : '### No specific angle — choose the strongest angle yourself based on the media.',
        iterationSection,
        '',
        '### Output format (JSON, strict):',
        '```json',
        '{',
        '  "hook": "The first line — must stop the scroll. ~10 words.",',
        '  "caption": "The full post body. Australian English. No inline hashtags.",',
        '  "hashtags": ["tag1", "tag2", "..."],',
        '  "post_type": "single" | "carousel" | "reel" | "video",',
        '  "rationale": "1-2 sentences explaining why this angle + format works for these media + this brand."',
        '}',
        '```',
        '',
        'Rules:',
        '- Return ONLY the JSON object, no preamble, no code fences in the final output, no explanation.',
        '- 5-8 hashtags, lowercase, no # prefix, mix broad (brand/category) and narrow (product/topic).',
        '- post_type should auto-fit: video media → reel (for IG/FB/TikTok) or video (YouTube/LinkedIn), multiple images → carousel, single image → single.',
        '- Match the brand voice you know from your memories. Australian English throughout.',
        '',
        // Speech-to-text mangles brand names, and tidying a mangled name into a
        // plausible one is how a product that does not exist reaches customers.
        // It has happened on the same video twice: "Bijous Saffron" became
        // "Bijou Saffron" once and "Bijou Zafran" the next — two inventions,
        // both confident, neither real. A proposal is where the name first gets
        // written down, so the check belongs here and not only downstream.
        'PRODUCT NAMES — CHECK, DO NOT GUESS.',
        'Collect EVERY uncertain product or brand name from the media and check them ALL in ONE verify_product call, passing the `products` array. A walkthrough names a dozen; one call each exhausts the step budget before the copy is written and the captions come out unverified.',
        'Only write a name whose verdict came back "exists". If it comes back not_found or uncertain, do NOT print it — refer to it naturally ("this one", "today\'s scent of the day") and say in the rationale that the owner needs to confirm which product it was.',
        'Tidying a garbled name into one that merely sounds right is the exact failure this prevents. A missing name is recoverable; a fabricated one published to customers is not.',
        '',
        '- verify_product is the ONLY tool to call. Once any names are settled, return the JSON and stop.',
      ]
        .filter(Boolean)
        .join('\n')

      // 5. Delegate to Content & Copy worker (its own model, memory, budget)
      const workerResult = await runAgentWorker(
        'content',
        brief,
        {
          supabase,
          userId,
          brandId,
          brand: typedBrand,
          conversationId: null,
        },
        {
          // Room to verify names before answering. At maxSteps 1 the worker
          // could not call verify_product at all, so an uncertain name had no
          // route other than being guessed.
          maxSteps: 6,
          timeoutMs: 120000,
        },
      )

      if (workerResult.error || !workerResult.result.trim()) {
        return `Content & Copy failed to produce a proposal: ${workerResult.error ?? 'empty response'}`
      }

      // 6. Parse the JSON envelope (Content & Copy is instructed to return strict JSON)
      let proposal: Partial<PostProposal> | null = null
      const cleaned = workerResult.result
        .trim()
        .replace(/^```(?:json)?\s*/i, '')
        .replace(/\s*```$/i, '')
        .trim()
      try {
        proposal = JSON.parse(cleaned)
      } catch {
        // Fall back: return the raw text so Director can still present it to user,
        // but flag that the structured parse failed
        return [
          '## Proposal (from Content & Copy — unstructured fallback)',
          '',
          workerResult.result,
          '',
          '*(Note: Content & Copy returned non-JSON — present this as text to the user and ask for feedback. Next iteration should return proper JSON.)*',
        ].join('\n')
      }

      if (!proposal?.caption || !Array.isArray(proposal.hashtags)) {
        return `Content & Copy returned malformed JSON: ${workerResult.result.slice(0, 400)}`
      }

      // Normalise hashtags (lowercase, strip #, strip spaces, cap at 10)
      const cleanHashtags = proposal.hashtags
        .filter((h): h is string => typeof h === 'string' && h.length > 0)
        .map((h) => h.replace(/^#/, '').replace(/\s+/g, '').toLowerCase())
        .slice(0, 10)

      // 7. Return structured proposal as a markdown block the Director can present verbatim
      const hashtagLine = cleanHashtags.map((h) => `#${h}`).join(' ')
      return [
        `## Proposal from Content & Copy for ${typedBrand.name} (${platform})`,
        '',
        `**Hook:** ${proposal.hook ?? '(no hook)'}`,
        '',
        `**Caption:**`,
        proposal.caption,
        '',
        `**Hashtags:** ${hashtagLine}`,
        '',
        `**Post type:** ${proposal.post_type ?? 'single'}`,
        '',
        proposal.rationale ? `**Why this works:** ${proposal.rationale}` : '',
        '',
        `**Media attached:** ${descriptors.map((d) => d.file_name).join(', ')}`,
        `**Media IDs:** ${descriptors.map((d) => d.id).join(', ')}`,
        '',
        '---',
        'Present this to the user. If they want changes, call propose_post_from_media again with the same media_ids + the full JSON above as `previous_proposal` + their feedback as `user_feedback`. When they approve, call draft_post with the finalised caption + hashtags + media_id.',
        '',
        '*Raw JSON for next iteration:*',
        '```json',
        JSON.stringify(
          {
            hook: proposal.hook ?? '',
            caption: proposal.caption,
            hashtags: cleanHashtags,
            post_type: proposal.post_type ?? 'single',
            rationale: proposal.rationale ?? '',
          },
          null,
          2,
        ),
        '```',
      ]
        .filter((l) => l !== '')
        .join('\n')
    },
  })
}
