import { NextResponse } from 'next/server'
import { Resend } from 'resend'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { generateApiKey } from '@/lib/auth/api-key'

const resend = new Resend(process.env.RESEND_API_KEY)

// GET — list team members for the authenticated owner
export async function GET() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

  const admin = createAdminClient()
  const { data: members, error } = await admin
    .from('team_members')
    .select('*')
    .eq('owner_id', user.id)
    .order('created_at', { ascending: true })

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  return NextResponse.json(members ?? [])
}

// POST — invite a new team member
export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

  const body = await request.json()
  const { email, role, brandIds } = body as {
    email?: string
    role?: 'admin' | 'viewer'
    brandIds?: string[] | null
  }

  if (!email) return NextResponse.json({ error: 'Email is required' }, { status: 400 })

  const normalised = email.toLowerCase().trim()
  if (normalised === user.email) {
    return NextResponse.json({ error: "You can't invite yourself" }, { status: 400 })
  }

  const admin = createAdminClient()

  // Check if already invited
  const { data: existing } = await admin
    .from('team_members')
    .select('id, status')
    .eq('owner_id', user.id)
    .eq('member_email', normalised)
    .single()

  if (existing?.status === 'accepted') {
    return NextResponse.json({ error: 'This person is already on your team' }, { status: 409 })
  }

  // Check if the invitee already has a Supabase account
  const { data: existingUser } = await admin
    .from('users')
    .select('id')
    .eq('email', normalised)
    .single()

  const memberData = {
    owner_id: user.id,
    member_email: normalised,
    member_id: existingUser?.id ?? null,
    role: role ?? 'viewer',
    brand_ids: brandIds ?? null,
    status: existingUser ? 'accepted' as const : 'pending' as const,
    accepted_at: existingUser ? new Date().toISOString() : null,
    invite_token: existingUser ? null : undefined, // auto-generated by DB default if pending
  }

  let member
  if (existing) {
    // Re-invite (update revoked → pending)
    const { data, error } = await admin
      .from('team_members')
      .update({ ...memberData, invite_token: existingUser ? null : crypto.randomUUID() })
      .eq('id', existing.id)
      .select()
      .single()
    if (error) return NextResponse.json({ error: error.message }, { status: 500 })
    member = data
  } else {
    const { data, error } = await admin.from('team_members').insert(memberData).select().single()
    if (error) return NextResponse.json({ error: error.message }, { status: 500 })
    member = data
  }

  // Get owner's name for the email
  const { data: ownerProfile } = await admin
    .from('users')
    .select('full_name, email')
    .eq('id', user.id)
    .single()

  const ownerName = ownerProfile?.full_name || ownerProfile?.email || 'Your colleague'

  // Get brand names if specific brands
  let brandNames = 'all brands'
  if (brandIds?.length) {
    const { data: brands } = await admin
      .from('brands')
      .select('name')
      .in('id', brandIds)
    brandNames = brands?.map(b => b.name).join(', ') || 'selected brands'
  }

  // Generate an API key for the invitee (for Claude Desktop / Cowork access)
  let apiKeyRaw: string | null = null
  const targetUserId = existingUser?.id ?? member.member_id
  if (targetUserId) {
    try {
      const { raw, hash, prefix } = generateApiKey()
      const keyHash = await hash
      await admin.from('api_keys').insert({
        user_id: targetUserId,
        name: `${ownerName}'s agency`,
        prefix,
        key_hash: keyHash,
      })
      apiKeyRaw = raw
    } catch (err) {
      console.error('[team] Failed to generate API key for invitee:', err)
    }
  }

  // Send invite email via Resend
  if (member.invite_token || existingUser) {
    const inviteUrl = existingUser
      ? `${process.env.NEXT_PUBLIC_SITE_URL || 'https://notrealsmart.com.au'}/agency`
      : `${process.env.NEXT_PUBLIC_SITE_URL || 'https://notrealsmart.com.au'}/invite/${member.invite_token}`

    const actionText = existingUser ? 'Go to Agency' : 'Accept Invitation'
    const statusText = existingUser
      ? `You already have an account, so you're all set. Click below to get started.`
      : `You'll need to create an account first. Click the button below — you'll set your email and password, then be taken straight to the agency. (Already have an account? Just go to <a href="${process.env.NEXT_PUBLIC_SITE_URL || 'https://notrealsmart.com.au'}/login" style="color:#1a1a1a;font-weight:500;">notrealsmart.com.au/login</a>)`

    // Step-by-step setup section for all platforms
    const mcpUrl = 'https://www.notrealsmart.com.au/api/mcp'
    const setupSection = `
            <div style="margin:28px 0;padding:24px;background:#f4f4f5;border-radius:12px;">
              <h2 style="font-size:18px;margin:0 0 16px;">How to use your agency</h2>

              <div style="margin:0 0 20px;">
                <h3 style="font-size:14px;margin:0 0 6px;color:#1a1a1a;">Option 1: Web app (easiest)</h3>
                <p style="font-size:13px;color:#666;line-height:1.5;margin:0;">
                  Just go to <a href="https://notrealsmart.com.au/agency" style="color:#1a1a1a;font-weight:500;">notrealsmart.com.au</a> and log in. Talk to the Director — it runs your marketing.
                </p>
              </div>

              <div style="margin:0 0 20px;">
                <h3 style="font-size:14px;margin:0 0 6px;color:#1a1a1a;">Option 2: Claude Desktop or Mobile (recommended)</h3>
                <ol style="font-size:13px;color:#666;line-height:1.8;margin:0;padding-left:20px;">
                  <li>Open Claude Desktop (or the Claude app on your phone)</li>
                  <li>Go to <strong>Settings → Integrations</strong></li>
                  <li>Click <strong>"Add custom connector"</strong></li>
                  <li>Name: <strong>NotRealSmart</strong></li>
                  <li>URL: <strong>${mcpUrl}</strong></li>
                  <li>Click <strong>Add</strong> — log in when prompted</li>
                  <li>Done! Your agency tools appear in every conversation</li>
                </ol>
              </div>

              <div style="margin:0 0 20px;">
                <h3 style="font-size:14px;margin:0 0 6px;color:#1a1a1a;">Option 3: Claude Code / Cowork (VS Code)</h3>
                <p style="font-size:13px;color:#666;line-height:1.5;margin:0 0 8px;">
                  Open Claude Code or Cowork and say:
                </p>
                <div style="background:#1a1a1a;color:#e4e4e7;padding:14px;border-radius:8px;font-family:'IBM Plex Mono',monospace;font-size:11px;line-height:1.6;word-break:break-all;">
                  Add an MCP server called "notrealsmart" with URL ${mcpUrl}${apiKeyRaw ? ` and authorization header "Bearer ${apiKeyRaw}"` : ''}
                </div>
                <p style="font-size:11px;color:#999;margin:6px 0 0;">
                  Claude does the config for you. No files to edit.
                </p>
              </div>

              <div style="padding:12px 16px;background:#fff;border-radius:8px;border:1px solid #e4e4e7;">
                <p style="font-size:13px;color:#444;margin:0;line-height:1.5;">
                  <strong>What you can do once connected:</strong><br/>
                  "Write a blog about X" · "Post this to Facebook" · "What's scheduled this week?" · "Audit my website" · "Write Instagram captions" · "Run a competitor scan"
                </p>
              </div>
            </div>`

    try {
      await resend.emails.send({
        from: process.env.RESEND_FROM_EMAIL ?? 'NRS Agency <noreply@notrealsmart.com.au>',
        to: normalised,
        subject: `${ownerName} invited you to join their agency on NotRealSmart`,
        html: `
          <div style="font-family:'IBM Plex Sans',system-ui,sans-serif;max-width:600px;margin:0 auto;padding:32px;color:#1a1a1a;">
            <h1 style="font-size:20px;margin:0 0 16px;">You've been invited!</h1>
            <p style="font-size:15px;line-height:1.6;color:#444;">
              <strong>${ownerName}</strong> has invited you to join their marketing agency as <strong>${role ?? 'viewer'}</strong>.
            </p>
            <p style="font-size:14px;color:#666;">
              You'll have access to <strong>${brandNames}</strong>.
            </p>
            <p style="font-size:14px;color:#666;">${statusText}</p>
            <div style="margin:24px 0;">
              <a href="${inviteUrl}" style="display:inline-block;background:#1a1a1a;color:#fff;padding:12px 28px;border-radius:8px;text-decoration:none;font-size:14px;font-weight:500;">
                ${actionText}
              </a>
            </div>
            ${setupSection}
            <p style="font-size:12px;color:#999;margin-top:32px;">
              NRS Agency by NotRealSmart &mdash; notrealsmart.com.au
            </p>
          </div>
        `,
      })
    } catch (err) {
      console.error('[team] Failed to send invite email:', err)
    }
  }

  return NextResponse.json(member, { status: 201 })
}
